---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: server
  run_list: 
    - bacula::server
  attributes: {}
- name: storage
  run_list: 
    - bacula::storage
  attributes: {}
- name: client
  run_list: 
    - bacula::client
  attributes: {}
- name: monitor
  run_list: 
    - bacula::bat
  attributes: {}
